import os
from dotenv import load_dotenv

load_dotenv()
# Change this to True on competition day
USE_GEMMA = False



def farmguardian_ai_response(prompt):

    """
    Main AI function used by FarmGuardian AI.

    Currently:
    - Uses prototype engine

    Competition day:
    - Switch to Gemma
    """

    if USE_GEMMA:

        return gemma_response(prompt)

    else:

        return prototype_response(prompt)



# ---------------------------------
# Temporary AI Engine
# ---------------------------------

def prototype_response(prompt):

    return {

        "analysis":
        """
Possible crop problem detected.

The farmer description suggests possible
crop stress caused by disease, pest attack,
or environmental conditions.

Further image reasoning will be handled
by Gemma multimodal intelligence.
        """,


        "risk":
        "Medium",


        "climate_warning":
        """
Monitor rainfall, soil moisture,
temperature and field conditions.
        """,


        "recommendations":[

            "Inspect affected crop areas",

            "Remove heavily damaged plant parts",

            "Monitor pests and disease symptoms",

            "Apply suitable agricultural practices"

        ]

    }



# ---------------------------------
# Gemma Connection
# ---------------------------------

def gemma_response(prompt):

    from google import genai


    client = genai.Client(
        api_key=os.getenv("GEMMA_API_KEY")
    )


    response = client.models.generate_content(

        model="gemma-4",

        contents=prompt

    )


    return {

        "analysis":
        response.text,


        "risk":
        "Generated by Gemma",


        "climate_warning":
        "Climate factors considered by Gemma",


        "recommendations":[

            response.text

        ]

    }

def detect_crop(description, farmer_crops):

    """
    Detect crop mentioned by farmer.
    """

    description = description.lower()

    for crop in farmer_crops:

        if crop.lower() in description:
            return crop


    # If no crop found
    return "Unknown crop"